language: php
sudo: false

branches:
  only:
    - master
    - develop

cache:
  directories:
    - ${HOME}/.composer/cache/files

php:
  - "7.1"

before_install:
  - .deploy/travis/check-env

install:
  - composer install

script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  api_key: ${FASTRESUME_API_HEROKU}
  on: master
