version: "3"

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ..:/usr/share/nginx/www/fastresume
            - ./services/nginx/fastresume-${FASTRESUME_DEPLOY_ENV}.conf:/etc/nginx/conf.d/default.conf

    php:
        image: fastresume_php
        build:
            context: ./
            dockerfile: ./services/php/dockerfile
            args:
                FASTRESUME_DEPLOY_ENV: ${FASTRESUME_DEPLOY_ENV}
                FASTRESUME_SYSTEM_USER_PHP: ${FASTRESUME_SYSTEM_USER_PHP}
        restart: always
        extra_hosts:
            - "docker_host:${FASTRESUME_DOCKER_HOST}"
        volumes:
            # folders
            - ..:/usr/share/nginx/www/fastresume
            - ${COMPOSER_HOME}:/composer
            # files
            - ./services/php/php-${FASTRESUME_DEPLOY_ENV}.ini:/usr/local/etc/php/php.ini
            - ./services/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        working_dir: /usr/share/nginx/www/fastresume
        environment:
            FASTRESUME_DEPLOY_ENV: ${FASTRESUME_DEPLOY_ENV}
            PHP_IDE_CONFIG: "serverName=docker"
